# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_converter:
       enabled: true
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader:
        default_format: json
    view:
        view_response_listener: true
        formats:
            xml: true
            json: true
            html: true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ xml, json ] }
            - { path: ^/, priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }
